name: Build LaTeX document
on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: skript.tex
      - name: Package
        shell: sh          
        run: |
          mkdir -p _site
          mv skript.pdf _site/ 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1          

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
